git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "node"
os:
  - osx

before_install:
  - gem install package_cloud
  - npm install -g electron-builder

install:
  - npm install

script:
  - npm run-script build
  - npm run-script buildOSX

branches:
  only:
    - master