git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "node"
  - "6"
  - "5"
os:
  - linux
  - osx
  
env:
  - TARGET_ARCH=x64
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
    - npm install

branches:
  only:
    - master